Article/config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  get "about", to:"pages#about"

  # resources :articles, only: [:show, :index, :new, :create, :edit, :update,:destroy] or
  resources :articles

  get "signup" , to:"users#new"

  resources :users, except: [:new]

  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'

  resources :categories
end

Article/app/models/user.rb
class User < ApplicationRecord

    before_save { self.email = email.downcase }
    
    validates :username, presence: true, 
                         uniqueness: { case_sensitive: false }, 
                         length: {minimum:3, maximum:25}

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i                     
    validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum:100},
                      format: { with: VALID_EMAIL_REGEX }


   has_many :articles, dependent: :destroy  #association part  
   
   has_secure_password


   
end

Article/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    helper_method :current_user, :logged_in?


    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end

      
      def logged_in?
        !!current_user
      end

      def require_user
        if !logged_in?
          flash[:alert] = "You must be logged in to perform that action"
          redirect_to login_path
        end
      end
end

Article/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_articles, only: [:show, :edit, :update, :destroy]

    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        # @article = Article.find(params[:id]) applying DRY principle here
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new 
        @article = Article.new
    end

    def edit
        # @article = Article.find(params[:id])
    end


    def create
        @article = Article.new(article_params)
        # render plain: @article.inspect
         
        @article.user = current_user

       if @article.save
        flash[:notice] = "Article Saved Successfully"
        # redirect_to article_path(@article) same as below
        redirect_to (@article)
       
       else
          render 'new'
       end
    end

    def update
        # @article = Article.find(params[:id])
       if @article.update(article_params)
        flash[:notice] = "Article Updated Successfully"
        redirect_to (@article)

        else 
            render 'edit'
        end
    end

    def destroy
        # @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    private 

    def set_articles
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
          flash[:alert] = "You can only edit or delete your own article"
          redirect_to @article
        end
      end



  


end

Article/app/controllers/categories_controller.rb
class CategoriesController <ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new
    end

    def show
        @articles = @category.articles
    end

    def index 
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def update
        if @category.update(category_params)
          flash[:notice] = "Your Category was successfully updated"
          redirect_to categories_path
        else
          render 'edit'
        end
        end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:noitce] = "Category Saved Successfully"
            redirect_to categories_path  

        else
            render 'new'
        end
    end

    def destroy
        @category.destroy 
        flash[:alert] = "Your Category was successfully Deleted"
        redirect_to categories_path  
      end
    
    private

    def set_user
        @category = Category.find(params[:id])
      end


    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
          flash[:alert] = "Only admins can perform that action"
          redirect_to categories_path
        end
      end
end

Article/app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home 

        redirect_to articles_path if logged_in?
    end
    def about 
    end
end

Article/app/controllers/sessions_controller.rb
class SessionsController <ApplicationController

    def new 

    end

    def create 
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged In Successfully"
            redirect_to articles_path

        else
            flash.now[:alert] = "There is something wrong with login detail "
            render "new"
        end

    end

    def destroy

        session[:user_id] = nil
        flash[:notice] = "Logged Out"
        redirect_to root_path

    end


end

Article/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :index, :show]
  before_action :require_same_user, only: [:edit, :update,:destroy]

    def show
        @articles = @user.articles
    end

    def new 
        @user = User.new
    end

    def index 
      @users = User.paginate(page: params[:page], per_page: 3)
    end

    def edit
         
    end

    def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to users_path
    else
      render 'edit'
    end
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
          redirect_to articles_path
        else
          flash[:alert] = "Something went wrong"
          render 'new'
        end
    end

    def destroy
    @user.destroy
    session[:user_id] = nil if !current_user.admin?
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to users_path 
     
  end


    

    private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end


  def set_user
    @user = User.find(params[:id])
  end


  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account"
      redirect_to @user
    end
  end


end

Article/app/views/articles/_articles.html.erb
 <table>
  <thead>
    <tr>
      <th>Title &nbsp; &nbsp;</th>
      <th>Description &nbsp; &nbsp;</th>
      <th>Categories  &nbsp; &nbsp; </th>
      <th> &nbsp; &nbsp;Article By  </th>
      <th>  Created at  </th>
      <th > &nbsp;  Updated at</th>
      <th>  &nbsp; &nbsp;Actions  </th>


    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td>  <% if article.categories.any? %>
              <%= render article.categories %> 
            <% end %>
         </td>
         <td>  <% if article.user %>
           &nbsp;&nbsp;   by <%= link_to article.user.username, user_path(article.user) %>
            <% end %> &nbsp; &nbsp; &nbsp;  
         </td>
        <td> <%= time_ago_in_words(article.created_at)%> &nbsp; &nbsp;&nbsp;</td>
        <td> &nbsp;&nbsp; <%= time_ago_in_words(article.updated_at) %> &nbsp;</td>
        <td>
        <%= link_to 'Show |', article %> 
        <% if logged_in? && (article.user == current_user || current_user.admin?)%>
        <%= link_to 'Edit |', edit_article_path(article) %>
        <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;
        <% end%>
        </td>
      </tr>
      
    <% end %>
  </tbody>
</table>

Article/app/views/articles/_form.html.erb
 

      <%= render 'shared/errors', obj: @article %>
      
        <%= form_with(model: @article, local: true) do |f| %>
           
            <%= f.label :title  %><br/>
            <%= f.text_field :title, placeholder: "Title of article" %> <br/><br/>
           

          
            <%= f.label :description%><br/>
            <%= f.text_area :description, placeholder: "Description of article" %><br/>

            <%= f.label :category%><br/>
           <%= f.collection_select(:category_ids, Category.all, :id, :name,
           { prompt: "Make your selection from below list"}, { multiple: true, size: 4}) %><br/><br/>
             
            <%= f.submit  %><br/>
         
        <% end %>
        <br/>
      
       
    
  

Article/app/views/articles/edit.html.erb
  <h1>Edit article</h1><br/>
  
  <%= render 'form' %>

  <%= link_to '[ Cancel and return to articles listing ]', articles_path %>
 

Article/app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Articles</title>

</head>

<body>
 
<h1>Listing all articles</h1>
<br/>


 
<%= render 'articles' %>
<br/>
<div class="digg_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

<br>

<div>
  <%= link_to "New Article", new_article_path%>
</div>

<%= link_to "All categories", categories_path %>

<p>
<%= link_to 'Home', root_path %>
</p>

</body>

</html>

Article/app/views/articles/new.html.erb
 
  <h1>Create a new article</h1>
  <%= render 'form' %>
 <%= link_to '[ Cancel and return to articles listing ]', articles_path %>


 

Article/app/views/articles/show.html.erb
<h1>Show Page</h1>

<h3  >Articles</h3>

 <%= render 'articles/articles' %>
 <br/>

  <p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>
<p>
  <strong>Categories:</strong>
 <% if @article.categories.any? %>
    <%= render @article.categories %>
 <% end %>
</p>
<p>
  <strong>Article By:</strong>
  <%= @article.user.username %>
</p>

 <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
<%= link_to 'Edit', edit_article_path(@article) %> |
<% end%>
<%= link_to 'Back', articles_path %>
<br/>

Article/app/views/pages/about.html.erb
<h1>About Page</h1>

<p>
<%= link_to 'Show Articles List', articles_path %>
</p>
<p>
<%= link_to 'Home', root_path %>
</p>

Article/app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
     
</head>
<body>

     

       <h1>Welcome To Home Page</h1>

       <%= link_to 'All Aricles', articles_path, class: "text-info" %><br/>
       <%= link_to "All categories", categories_path, class: "text-info" %>
       <br/>
        
        
          
         
     

      
 
</body>
</html>